# Generated by Django 3.2.5 on 2023-12-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mosaic', '0005_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
