# Generated by Django 3.2.5 on 2023-12-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mosaic', '0008_auto_20231224_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room_name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
