# Generated by Django 3.2.5 on 2023-12-25 11:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Mosaic', '0010_remove_message_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 25, 11, 31, 1, 791747, tzinfo=utc)),
        ),
    ]
