# Generated by Django 3.2.5 on 2023-12-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mosaic', '0012_alter_comment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
