# Generated by Django 4.2.4 on 2023-12-26 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mosaic', '0013_post_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
    ]
