# Generated by Django 3.2.5 on 2023-12-26 19:19

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Mosaic', '0014_remove_profile_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
