# Generated by Django 3.2.5 on 2023-12-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mosaic', '0015_profile_phone_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
