# Generated by Django 3.2.5 on 2023-12-29 17:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Mosaic', '0018_auto_20231229_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='expiration_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 5, 17, 9, 57, 714511, tzinfo=utc)),
        ),
    ]
